apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore2
  namespace: ns2
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: "localhost:6379"
  - name: actorStateStore
    value: "true"
  - name: redisDB
    value: "2"