apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore1
  namespace: ns1
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: redis-password
  - name: actorStateStore
    value: "true"
  - name: redisDB
    value: "1"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore2
  namespace: ns2
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-secret
      key: redis-password
  - name: actorStateStore
    value: "true"
  - name: redisDB
    value: "2"